/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import niti.ServerNit;

/**
 *
 * @author Nikola
 */
public class ServerskaForma extends javax.swing.JFrame {

    private ServerNit serverskaNit;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        srediFormu();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemPokreniServer = new javax.swing.JMenuItem();
        jMenuItemZaustaviServer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        jLabel1.setText("Status servera:");

        jMenu1.setText("Server");

        jMenuItemPokreniServer.setText("Pokreni server");
        jMenuItemPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPokreniServerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPokreniServer);

        jMenuItemZaustaviServer.setText("Zaustavi server");
        jMenuItemZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZaustaviServerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemZaustaviServer);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Konfiguracija");

        miPort.setText("Port");
        miPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPortActionPerformed(evt);
            }
        });
        jMenu2.add(miPort);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(445, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStatus))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPokreniServerActionPerformed
        // TODO add your handling code here:
        if (serverskaNit == null || !serverskaNit.isAlive()) {
            try {
                serverskaNit = new ServerNit();
            } catch (IOException ex) {
                Logger.getLogger(ServerskaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            serverskaNit.start();
            jMenuItemPokreniServer.setEnabled(false);
            jMenuItemZaustaviServer.setEnabled(true);
            miPort.setEnabled(false);
            lblStatus.setText(" Pokrenut");
        } else {
            System.err.println("Serverska nit je pokrenuta!");
        }
    }//GEN-LAST:event_jMenuItemPokreniServerActionPerformed

    private void jMenuItemZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZaustaviServerActionPerformed
        // TODO add your handling code here:

        if (serverskaNit.getServerSocket() != null && serverskaNit.getServerSocket().isBound()) {
            try {
                serverskaNit.getServerSocket().close();
                lblStatus.setText(" Ugasen");
                jMenuItemPokreniServer.setEnabled(true);
                jMenuItemZaustaviServer.setEnabled(false);
                miPort.setEnabled(true);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }//GEN-LAST:event_jMenuItemZaustaviServerActionPerformed

    private void miPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPortActionPerformed
        // TODO add your handling code here:
        PortDialog port = new PortDialog(this, rootPaneCheckingEnabled);
        port.setVisible(true);
    }//GEN-LAST:event_miPortActionPerformed

    /**
     * @param args the command line arguments
     */
    private void pokreniServer() throws IOException {
        ServerNit psn = new ServerNit();
        psn.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPokreniServer;
    private javax.swing.JMenuItem jMenuItemZaustaviServer;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuItem miPort;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jMenuItemZaustaviServer.setEnabled(false);
        setLocationRelativeTo(null);

    }

}
