/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Nikola
 */
public class FrmAdminUnosSudije extends javax.swing.JDialog {

    /**
     * Creates new form FrmAdminUnosSudije
     */
    public FrmAdminUnosSudije(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtProfesija = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtZemlja = new javax.swing.JTextField();
        lblErrorKorisnickoIme = new javax.swing.JLabel();
        lblErrorLozinka = new javax.swing.JLabel();
        lblErrorIme = new javax.swing.JLabel();
        lblErrorPrezime = new javax.swing.JLabel();
        lblErrorMail = new javax.swing.JLabel();
        lblErrorProfesija = new javax.swing.JLabel();
        lblErrorZemlja = new javax.swing.JLabel();
        txtLozinka = new javax.swing.JPasswordField();
        btnSacuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos sudije"));
        jPanel1.setToolTipText("");

        jLabel1.setText("Korisnicko ime:");

        txtKorisnickoIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKorisnickoImeKeyReleased(evt);
            }
        });

        jLabel2.setText("Lozinka:");

        jLabel3.setText("Ime:");

        jLabel4.setText("Prezime:");

        jLabel5.setText("Mail:");

        jLabel6.setText("Profesija:");

        txtProfesija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfesijaActionPerformed(evt);
            }
        });

        jLabel7.setText("Zemlja:");

        lblErrorKorisnickoIme.setText("jLabel8");

        lblErrorLozinka.setText("jLabel9");

        lblErrorIme.setText("jLabel10");

        lblErrorPrezime.setText("jLabel11");

        lblErrorMail.setText("jLabel12");

        lblErrorProfesija.setText("jLabel13");

        lblErrorZemlja.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKorisnickoIme))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMail)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime)
                            .addComponent(txtProfesija)
                            .addComponent(txtZemlja)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorProfesija)
                                    .addComponent(lblErrorMail)
                                    .addComponent(lblErrorPrezime)
                                    .addComponent(lblErrorIme)
                                    .addComponent(lblErrorLozinka)
                                    .addComponent(lblErrorKorisnickoIme)
                                    .addComponent(lblErrorZemlja))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLozinka))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorKorisnickoIme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorLozinka)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblErrorIme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblErrorPrezime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMail)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProfesija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorProfesija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtZemlja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorZemlja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvaj.setText("Sacuvaj");

        btnOtkazi.setText("Otkazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 133, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOtkazi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProfesijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfesijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfesijaActionPerformed

    private void txtKorisnickoImeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKorisnickoImeKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtKorisnickoImeKeyReleased

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorIme;
    private javax.swing.JLabel lblErrorKorisnickoIme;
    private javax.swing.JLabel lblErrorLozinka;
    private javax.swing.JLabel lblErrorMail;
    private javax.swing.JLabel lblErrorPrezime;
    private javax.swing.JLabel lblErrorProfesija;
    private javax.swing.JLabel lblErrorZemlja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtLozinka;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtProfesija;
    private javax.swing.JTextField txtZemlja;
    // End of variables declaration//GEN-END:variables

    public void addBtnSacuvajListener(ActionListener ae) {
        btnSacuvaj.addActionListener(ae);
    }

    public void addBtnOtkaziActionListener(ActionListener ae) {
        btnOtkazi.addActionListener(ae);
    }

    public javax.swing.JButton getBtnOtkazi() {
        return btnOtkazi;
    }

    public void setBtnOtkazi(javax.swing.JButton btnOtkazi) {
        this.btnOtkazi = btnOtkazi;
    }

    public javax.swing.JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public void setBtnSacuvaj(javax.swing.JButton btnSacuvaj) {
        this.btnSacuvaj = btnSacuvaj;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JLabel getLblErrorIme() {
        return lblErrorIme;
    }

    public void setLblErrorIme(javax.swing.JLabel lblErrorIme) {
        this.lblErrorIme = lblErrorIme;
    }

    public javax.swing.JLabel getLblErrorKorisnickoIme() {
        return lblErrorKorisnickoIme;
    }

    public void setLblErrorKorisnickoIme(javax.swing.JLabel lblErrorKorisnickoIme) {
        this.lblErrorKorisnickoIme = lblErrorKorisnickoIme;
    }

    public javax.swing.JLabel getLblErrorLozinka() {
        return lblErrorLozinka;
    }

    public void setLblErrorLozinka(javax.swing.JLabel lblErrorLozinka) {
        this.lblErrorLozinka = lblErrorLozinka;
    }

    public javax.swing.JLabel getLblErrorMail() {
        return lblErrorMail;
    }

    public void setLblErrorMail(javax.swing.JLabel lblErrorMail) {
        this.lblErrorMail = lblErrorMail;
    }

    public javax.swing.JLabel getLblErrorPrezime() {
        return lblErrorPrezime;
    }

    public void setLblErrorPrezime(javax.swing.JLabel lblErrorPrezime) {
        this.lblErrorPrezime = lblErrorPrezime;
    }

    public javax.swing.JLabel getLblErrorProfesija() {
        return lblErrorProfesija;
    }

    public void setLblErrorProfesija(javax.swing.JLabel lblErrorProfesija) {
        this.lblErrorProfesija = lblErrorProfesija;
    }

    public javax.swing.JLabel getLblErrorZemlja() {
        return lblErrorZemlja;
    }

    public void setLblErrorZemlja(javax.swing.JLabel lblErrorZemlja) {
        this.lblErrorZemlja = lblErrorZemlja;
    }

    public javax.swing.JTextField getTxtIme() {
        return txtIme;
    }

    public void setTxtIme(javax.swing.JTextField txtIme) {
        this.txtIme = txtIme;
    }

    public javax.swing.JTextField getTxtKorisnickoIme() {
        return txtKorisnickoIme;
    }

    public void setTxtKorisnickoIme(javax.swing.JTextField txtKorisnickoIme) {
        this.txtKorisnickoIme = txtKorisnickoIme;
    }

    public javax.swing.JTextField getTxtLozinka() {
        return txtLozinka;
    }

    public void setTxtLozinka(javax.swing.JPasswordField txtLozinka) {
        this.txtLozinka = txtLozinka;
    }

    public javax.swing.JTextField getTxtMail() {
        return txtMail;
    }

    public void setTxtMail(javax.swing.JTextField txtMail) {
        this.txtMail = txtMail;
    }

    public javax.swing.JTextField getTxtPrezime() {
        return txtPrezime;
    }

    public void setTxtPrezime(javax.swing.JTextField txtPrezime) {
        this.txtPrezime = txtPrezime;
    }

    public javax.swing.JTextField getTxtProfesija() {
        return txtProfesija;
    }

    public void setTxtProfesija(javax.swing.JTextField txtProfesija) {
        this.txtProfesija = txtProfesija;
    }

    public javax.swing.JTextField getTxtZemlja() {
        return txtZemlja;
    }

    public void setTxtZemlja(javax.swing.JTextField txtZemlja) {
        this.txtZemlja = txtZemlja;
    }
}
