/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Nikola
 */
public class FrmAdminUnosHakatona extends javax.swing.JDialog {

    /**
     * Creates new form FrmAdminUnosHakatona
     */
    public FrmAdminUnosHakatona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUnosHakatona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNazivHakatona = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateChooserDatum = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSudija = new javax.swing.JTable();
        lblErrorNaziv = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlIzborSudije = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIzborSudije = new javax.swing.JTable();
        btnDodajSudiju = new javax.swing.JButton();
        btnIzbaciSudiju = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos hakatona");

        pnlUnosHakatona.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos hakatona"));

        jLabel1.setText("Naziv:");

        jLabel2.setText("Datum:");

        tblSudija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSudija);

        lblErrorNaziv.setText("jLabel3");

        jLabel3.setText("Sudije:");

        pnlIzborSudije.setBorder(javax.swing.BorderFactory.createTitledBorder("Izbor sudije"));

        tblIzborSudije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblIzborSudije);

        javax.swing.GroupLayout pnlIzborSudijeLayout = new javax.swing.GroupLayout(pnlIzborSudije);
        pnlIzborSudije.setLayout(pnlIzborSudijeLayout);
        pnlIzborSudijeLayout.setHorizontalGroup(
            pnlIzborSudijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzborSudijeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIzborSudijeLayout.setVerticalGroup(
            pnlIzborSudijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzborSudijeLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDodajSudiju.setText("<   Dodaj sudiju");

        btnIzbaciSudiju.setText("Izbaci sudiju  >");
        btnIzbaciSudiju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciSudijuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnosHakatonaLayout = new javax.swing.GroupLayout(pnlUnosHakatona);
        pnlUnosHakatona.setLayout(pnlUnosHakatonaLayout);
        pnlUnosHakatonaLayout.setHorizontalGroup(
            pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                        .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrorNaziv)
                            .addComponent(txtNazivHakatona)
                            .addComponent(dateChooserDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDodajSudiju)
                            .addComponent(btnIzbaciSudiju, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlIzborSudije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        pnlUnosHakatonaLayout.setVerticalGroup(
            pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlIzborSudije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                        .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNazivHakatona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(lblErrorNaziv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGroup(pnlUnosHakatonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(pnlUnosHakatonaLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnDodajSudiju)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzbaciSudiju)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        btnOtkazi.setText("Otkazi");

        btnSacuvaj.setText("Sacuvaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(626, Short.MAX_VALUE)
                .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUnosHakatona, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnosHakatona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnSacuvaj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzbaciSudijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciSudijuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzbaciSudijuActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajSudiju;
    private javax.swing.JButton btnIzbaciSudiju;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private datechooser.beans.DateChooserCombo dateChooserDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorNaziv;
    private javax.swing.JPanel pnlIzborSudije;
    private javax.swing.JPanel pnlUnosHakatona;
    private javax.swing.JTable tblIzborSudije;
    private javax.swing.JTable tblSudija;
    private javax.swing.JTextField txtNazivHakatona;
    // End of variables declaration//GEN-END:variables

    public void addBtnDodajSudijuListener(ActionListener ae) {
        btnDodajSudiju.addActionListener(ae);
    }

    public void addBtnIzbaciSudijuListener(ActionListener ae) {
        btnIzbaciSudiju.addActionListener(ae);
    }

    public void addBtnSacuvajActionListener(ActionListener ae) {
        btnSacuvaj.addActionListener(ae);
    }

    public void addBtnOtkaziActionListener(ActionListener ae) {
        btnOtkazi.addActionListener(ae);
    }

    public javax.swing.JButton getBtnDodajSudiju() {
        return btnDodajSudiju;
    }

    public void setBtnDodajSudiju(javax.swing.JButton btnDodajSudiju) {
        this.btnDodajSudiju = btnDodajSudiju;
    }

    public javax.swing.JButton getBtnOtkazi() {
        return btnOtkazi;
    }

    public void setBtnOtkazi(javax.swing.JButton btnOtkazi) {
        this.btnOtkazi = btnOtkazi;
    }

    public javax.swing.JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public void setBtnSacuvaj(javax.swing.JButton btnSacuvaj) {
        this.btnSacuvaj = btnSacuvaj;
    }

    public datechooser.beans.DateChooserCombo getDateChooserDatum() {
        return dateChooserDatum;
    }

    public void setDateChooserDatum(datechooser.beans.DateChooserCombo dateChooserDatum) {
        this.dateChooserDatum = dateChooserDatum;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public javax.swing.JPanel getjPanel1() {
        return pnlUnosHakatona;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.pnlUnosHakatona = jPanel1;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JLabel getLblErrorNaziv() {
        return lblErrorNaziv;
    }

    public void setLblErrorNaziv(javax.swing.JLabel lblErrorNaziv) {
        this.lblErrorNaziv = lblErrorNaziv;
    }

    public javax.swing.JTable getTblSudija() {
        return tblSudija;
    }

    public void setTblSudija(javax.swing.JTable tblSudija) {
        this.tblSudija = tblSudija;
    }

    public javax.swing.JTextField getTxtNazivHakatona() {
        return txtNazivHakatona;
    }

    public void setTxtNazivHakatona(javax.swing.JTextField txtNazivHakatona) {
        this.txtNazivHakatona = txtNazivHakatona;
    }

    public javax.swing.JButton getBtnIzbaciSudiju() {
        return btnIzbaciSudiju;
    }

    public void setBtnIzbaciSudiju(javax.swing.JButton btnIzbaciSudiju) {
        this.btnIzbaciSudiju = btnIzbaciSudiju;
    }

    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public javax.swing.JPanel getPnlIzborSudije() {
        return pnlIzborSudije;
    }

    public void setPnlIzborSudije(javax.swing.JPanel pnlIzborSudije) {
        this.pnlIzborSudije = pnlIzborSudije;
    }

    public javax.swing.JPanel getPnlUnosHakatona() {
        return pnlUnosHakatona;
    }

    public void setPnlUnosHakatona(javax.swing.JPanel pnlUnosHakatona) {
        this.pnlUnosHakatona = pnlUnosHakatona;
    }

    public javax.swing.JTable getTblIzborSudije() {
        return tblIzborSudije;
    }

    public void setTblIzborSudije(javax.swing.JTable tblIzborSudije) {
        this.tblIzborSudije = tblIzborSudije;
    }
    
}
