/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Nikola
 */
public class FrmAdminGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministrator
     */
    public FrmAdminGlavna() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPretraga = new javax.swing.JPanel();
        lblPrijavljeniAdministrator = new javax.swing.JLabel();
        btnKrajRada = new javax.swing.JButton();
        mbarGLavnimeni = new javax.swing.JMenuBar();
        menuGlavniMeni = new javax.swing.JMenu();
        menuHakaton = new javax.swing.JMenu();
        miPregledHakaton = new javax.swing.JMenuItem();
        miUnosHakaton = new javax.swing.JMenuItem();
        menuSudija = new javax.swing.JMenu();
        miPregledSudija = new javax.swing.JMenuItem();
        miUnosSudija = new javax.swing.JMenuItem();
        menuMentor = new javax.swing.JMenu();
        miPregledMentor = new javax.swing.JMenuItem();
        miUnosMentor = new javax.swing.JMenuItem();
        menuTim = new javax.swing.JMenu();
        miUnosTim = new javax.swing.JMenuItem();
        miPregledTim = new javax.swing.JMenuItem();
        menuPregledClana = new javax.swing.JMenu();
        miPregledClana = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");

        javax.swing.GroupLayout pnlPretragaLayout = new javax.swing.GroupLayout(pnlPretraga);
        pnlPretraga.setLayout(pnlPretragaLayout);
        pnlPretragaLayout.setHorizontalGroup(
            pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPretragaLayout.setVerticalGroup(
            pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        lblPrijavljeniAdministrator.setText("Prijavljeni admin: ");

        btnKrajRada.setText("Kraj rada");
        btnKrajRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrajRadaActionPerformed(evt);
            }
        });

        menuGlavniMeni.setText("Glavni meni");

        menuHakaton.setText("Hakaton");

        miPregledHakaton.setText("Pregled");
        menuHakaton.add(miPregledHakaton);

        miUnosHakaton.setText("Unos");
        menuHakaton.add(miUnosHakaton);

        menuGlavniMeni.add(menuHakaton);

        menuSudija.setText("Sudija");

        miPregledSudija.setText("Pregled");
        menuSudija.add(miPregledSudija);

        miUnosSudija.setText("Unos");
        miUnosSudija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosSudijaActionPerformed(evt);
            }
        });
        menuSudija.add(miUnosSudija);

        menuGlavniMeni.add(menuSudija);

        menuMentor.setText("Mentor");

        miPregledMentor.setText("Pregled");
        menuMentor.add(miPregledMentor);

        miUnosMentor.setText("Unos");
        menuMentor.add(miUnosMentor);

        menuGlavniMeni.add(menuMentor);

        menuTim.setText("Tim");

        miUnosTim.setText("Unos");
        menuTim.add(miUnosTim);

        miPregledTim.setText("Pregled");
        menuTim.add(miPregledTim);

        menuGlavniMeni.add(menuTim);

        menuPregledClana.setText("Clan");

        miPregledClana.setText("Pregled");
        menuPregledClana.add(miPregledClana);

        menuGlavniMeni.add(menuPregledClana);

        mbarGLavnimeni.add(menuGlavniMeni);

        setJMenuBar(mbarGLavnimeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPretraga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrijavljeniAdministrator)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(431, 431, 431)
                                .addComponent(btnKrajRada, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(431, 431, 431)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrijavljeniAdministrator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnKrajRada)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUnosSudijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosSudijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miUnosSudijaActionPerformed

    private void btnKrajRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrajRadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKrajRadaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKrajRada;
    private javax.swing.JLabel lblPrijavljeniAdministrator;
    private javax.swing.JMenuBar mbarGLavnimeni;
    private javax.swing.JMenu menuGlavniMeni;
    private javax.swing.JMenu menuHakaton;
    private javax.swing.JMenu menuMentor;
    private javax.swing.JMenu menuPregledClana;
    private javax.swing.JMenu menuSudija;
    private javax.swing.JMenu menuTim;
    private javax.swing.JMenuItem miPregledClana;
    private javax.swing.JMenuItem miPregledHakaton;
    private javax.swing.JMenuItem miPregledMentor;
    private javax.swing.JMenuItem miPregledSudija;
    private javax.swing.JMenuItem miPregledTim;
    private javax.swing.JMenuItem miUnosHakaton;
    private javax.swing.JMenuItem miUnosMentor;
    private javax.swing.JMenuItem miUnosSudija;
    private javax.swing.JMenuItem miUnosTim;
    private javax.swing.JPanel pnlPretraga;
    // End of variables declaration//GEN-END:variables

    public void addMiUnosTimaListener(ActionListener ae) {
        miUnosTim.addActionListener(ae);
    }

    public void addMiPregledTimovaListener(ActionListener ae) {
        miPregledTim.addActionListener(ae);
    }

    public void addMIPregledClanovaListener(ActionListener ae) {
        miPregledClana.addActionListener(ae);
    }

    public void addMiUnosHakatonaListener(ActionListener ae) {
        miUnosHakaton.addActionListener(ae);
    }

    public void addBtnKrajRadaListener(ActionListener ae) {
        btnKrajRada.addActionListener(ae);
    }

    public void addMiPregledHakatonaListener(ActionListener ae) {
        miPregledHakaton.addActionListener(ae);
    }

    public void addMiUnosSudijeActionListener(ActionListener ae) {
        miUnosSudija.addActionListener(ae);
    }

    public void addMiPregledSuijeActionListener(ActionListener ae) {
        miPregledSudija.addActionListener(ae);
    }

    public void addMiUnosMentoraActionListener(ActionListener ae) {
        miUnosMentor.addActionListener(ae);
    }

    public void addMiPregledMentoraActionListener(ActionListener ae) {
        miPregledMentor.addActionListener(ae);
    }

    public javax.swing.JMenuBar getMbarGLavnimeni() {
        return mbarGLavnimeni;
    }

    public void setMbarGLavnimeni(javax.swing.JMenuBar mbarGLavnimeni) {
        this.mbarGLavnimeni = mbarGLavnimeni;
    }

    public javax.swing.JMenu getMenuGlavniMeni() {
        return menuGlavniMeni;
    }

    public void setMenuGlavniMeni(javax.swing.JMenu menuGlavniMeni) {
        this.menuGlavniMeni = menuGlavniMeni;
    }

    public javax.swing.JMenu getMenuHakaton() {
        return menuHakaton;
    }

    public void setMenuHakaton(javax.swing.JMenu menuHakaton) {
        this.menuHakaton = menuHakaton;
    }

    public javax.swing.JMenu getMenuMentor() {
        return menuMentor;
    }

    public void setMenuMentor(javax.swing.JMenu menuMentor) {
        this.menuMentor = menuMentor;
    }

    public javax.swing.JMenu getMenuSudija() {
        return menuSudija;
    }

    public void setMenuSudija(javax.swing.JMenu menuSudija) {
        this.menuSudija = menuSudija;
    }

    public javax.swing.JMenuItem getMiPregledHakaton() {
        return miPregledHakaton;
    }

    public void setMiPregledHakaton(javax.swing.JMenuItem miPregledHakaton) {
        this.miPregledHakaton = miPregledHakaton;
    }

    public javax.swing.JMenuItem getMiPregledMentor() {
        return miPregledMentor;
    }

    public void setMiPregledMentor(javax.swing.JMenuItem miPregledMentor) {
        this.miPregledMentor = miPregledMentor;
    }

    public javax.swing.JMenuItem getMiPregledSudija() {
        return miPregledSudija;
    }

    public void setMiPregledSudija(javax.swing.JMenuItem miPregledSudija) {
        this.miPregledSudija = miPregledSudija;
    }

    public javax.swing.JMenuItem getMiUnosHakaton() {
        return miUnosHakaton;
    }

    public void setMiUnosHakaton(javax.swing.JMenuItem miUnosHakaton) {
        this.miUnosHakaton = miUnosHakaton;
    }

    public javax.swing.JMenuItem getMiUnosMentor() {
        return miUnosMentor;
    }

    public void setMiUnosMentor(javax.swing.JMenuItem miUnosMentor) {
        this.miUnosMentor = miUnosMentor;
    }

    public javax.swing.JMenuItem getMiUnosSudija() {
        return miUnosSudija;
    }

    public void setMiUnosSudija(javax.swing.JMenuItem miUnosSudija) {
        this.miUnosSudija = miUnosSudija;
    }

    public javax.swing.JPanel getPnlPretraga() {
        return pnlPretraga;
    }

    public void setPnlPretraga(javax.swing.JPanel pnlPretraga) {
        this.pnlPretraga = pnlPretraga;
    }

    public javax.swing.JLabel getLblPrijavljeniAdministrator() {
        return lblPrijavljeniAdministrator;
    }

    public void setLblPrijavljeniAdministrator(javax.swing.JLabel lblPrijavljeniAdministrator) {
        this.lblPrijavljeniAdministrator = lblPrijavljeniAdministrator;
    }

    public javax.swing.JButton getBtnKrajRada() {
        return btnKrajRada;
    }

    public void setBtnKrajRada(javax.swing.JButton btnKrajRada) {
        this.btnKrajRada = btnKrajRada;
    }

    public javax.swing.JMenu getMenuTim() {
        return menuTim;
    }

    public void setMenuTim(javax.swing.JMenu menuTim) {
        this.menuTim = menuTim;
    }

    public javax.swing.JMenuItem getMiPregledTim() {
        return miPregledTim;
    }

    public void setMiPregledTim(javax.swing.JMenuItem miPregledTim) {
        this.miPregledTim = miPregledTim;
    }

    public javax.swing.JMenuItem getMiUnosTim() {
        return miUnosTim;
    }

    public void setMiUnosTim(javax.swing.JMenuItem miUnosTim) {
        this.miUnosTim = miUnosTim;
    }

}
