/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Nikola
 */
public class FrmSudijaTim extends javax.swing.JDialog {

    /**
     * Creates new form FrmSudijaTim
     */
    public FrmSudijaTim(FrmSudijaHakaton parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetaljiTima = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNazivTima = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMentorTima = new javax.swing.JTextField();
        pnlClanoviTima = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        pnlOcena = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDizajn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEfikasnost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSlozenost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKomentar = new javax.swing.JTextArea();
        btnOceni = new javax.swing.JButton();
        lblOcenjen = new javax.swing.JLabel();
        lblErrorDizajn = new javax.swing.JLabel();
        lblErrprEfikasnost = new javax.swing.JLabel();
        lblErrorSlozenost = new javax.swing.JLabel();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tim");

        pnlDetaljiTima.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalji tima"));

        jLabel1.setText("Naziv:");

        jLabel2.setText("Mentor:");

        pnlClanoviTima.setBorder(javax.swing.BorderFactory.createTitledBorder("Clanovi tima"));

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClanovi);

        javax.swing.GroupLayout pnlClanoviTimaLayout = new javax.swing.GroupLayout(pnlClanoviTima);
        pnlClanoviTima.setLayout(pnlClanoviTimaLayout);
        pnlClanoviTimaLayout.setHorizontalGroup(
            pnlClanoviTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClanoviTimaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlClanoviTimaLayout.setVerticalGroup(
            pnlClanoviTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClanoviTimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlOcena.setBorder(javax.swing.BorderFactory.createTitledBorder("Ocena"));

        jLabel3.setText("Dizajn:");

        jLabel4.setText("Efikasnost:");

        jLabel5.setText("Slozenost:");

        jLabel6.setText("Komentar:");

        txtKomentar.setColumns(20);
        txtKomentar.setRows(5);
        jScrollPane2.setViewportView(txtKomentar);

        btnOceni.setText("Oceni");

        lblOcenjen.setText("Tim je ocenjen.");

        lblErrorDizajn.setText("ErrorDizajn");

        lblErrprEfikasnost.setText("ErrorEfikasnost");

        lblErrorSlozenost.setText("ErrorSlozenost");

        javax.swing.GroupLayout pnlOcenaLayout = new javax.swing.GroupLayout(pnlOcena);
        pnlOcena.setLayout(pnlOcenaLayout);
        pnlOcenaLayout.setHorizontalGroup(
            pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOcenaLayout.createSequentialGroup()
                        .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDizajn)
                            .addGroup(pnlOcenaLayout.createSequentialGroup()
                                .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrprEfikasnost)
                                    .addComponent(lblErrorDizajn))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOcenaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtEfikasnost, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlOcenaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOcenaLayout.createSequentialGroup()
                                .addComponent(lblErrorSlozenost)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblOcenjen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOcenaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOceni, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOcenaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSlozenost, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlOcenaLayout.setVerticalGroup(
            pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOcenaLayout.createSequentialGroup()
                        .addComponent(txtDizajn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorDizajn))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEfikasnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrprEfikasnost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSlozenost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorSlozenost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOcenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblOcenjen)
                .addGap(18, 18, 18)
                .addComponent(btnOceni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDetaljiTimaLayout = new javax.swing.GroupLayout(pnlDetaljiTima);
        pnlDetaljiTima.setLayout(pnlDetaljiTimaLayout);
        pnlDetaljiTimaLayout.setHorizontalGroup(
            pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetaljiTimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlClanoviTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDetaljiTimaLayout.createSequentialGroup()
                        .addGroup(pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivTima)
                            .addComponent(txtMentorTima))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlOcena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetaljiTimaLayout.setVerticalGroup(
            pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetaljiTimaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDetaljiTimaLayout.createSequentialGroup()
                        .addGroup(pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNazivTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetaljiTimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMentorTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlClanoviTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btnOtkazi.setText("Otkazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetaljiTima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetaljiTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOtkazi)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOceni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorDizajn;
    private javax.swing.JLabel lblErrorSlozenost;
    private javax.swing.JLabel lblErrprEfikasnost;
    private javax.swing.JLabel lblOcenjen;
    private javax.swing.JPanel pnlClanoviTima;
    private javax.swing.JPanel pnlDetaljiTima;
    private javax.swing.JPanel pnlOcena;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTextField txtDizajn;
    private javax.swing.JTextField txtEfikasnost;
    private javax.swing.JTextArea txtKomentar;
    private javax.swing.JTextField txtMentorTima;
    private javax.swing.JTextField txtNazivTima;
    private javax.swing.JTextField txtSlozenost;
    // End of variables declaration//GEN-END:variables

    public void addButtonOceniListener(ActionListener ae){
        btnOceni.addActionListener(ae);
    }
    public void addButtonOtkaziListener(ActionListener ae){
        btnOtkazi.addActionListener(ae);
    }
    public javax.swing.JButton getBtnOceni() {
        return btnOceni;
    }

    public void setBtnOceni(javax.swing.JButton btnOceni) {
        this.btnOceni = btnOceni;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public javax.swing.JTable getjTable1() {
        return tblClanovi;
    }

    public void setjTable1(javax.swing.JTable jTable1) {
        this.tblClanovi = jTable1;
    }

    public javax.swing.JLabel getLblOcenjen() {
        return lblOcenjen;
    }

    public void setLblOcenjen(javax.swing.JLabel lblOcenjen) {
        this.lblOcenjen = lblOcenjen;
    }

    public javax.swing.JPanel getPnlClanoviTima() {
        return pnlClanoviTima;
    }

    public void setPnlClanoviTima(javax.swing.JPanel pnlClanoviTima) {
        this.pnlClanoviTima = pnlClanoviTima;
    }

    public javax.swing.JPanel getPnlDetaljiTima() {
        return pnlDetaljiTima;
    }

    public void setPnlDetaljiTima(javax.swing.JPanel pnlDetaljiTima) {
        this.pnlDetaljiTima = pnlDetaljiTima;
    }

    public javax.swing.JPanel getPnlOcena() {
        return pnlOcena;
    }

    public void setPnlOcena(javax.swing.JPanel pnlOcena) {
        this.pnlOcena = pnlOcena;
    }

    public javax.swing.JTextField getTxtDizajn() {
        return txtDizajn;
    }

    public void setTxtDizajn(javax.swing.JTextField txtDizajn) {
        this.txtDizajn = txtDizajn;
    }

    public javax.swing.JTextField getTxtEfikasnost() {
        return txtEfikasnost;
    }

    public void setTxtEfikasnost(javax.swing.JTextField txtEfikasnost) {
        this.txtEfikasnost = txtEfikasnost;
    }

    public javax.swing.JTextArea getTxtKomentar() {
        return txtKomentar;
    }

    public void setTxtKomentar(javax.swing.JTextArea txtKomentar) {
        this.txtKomentar = txtKomentar;
    }

    public javax.swing.JTextField getTxtMentorTima() {
        return txtMentorTima;
    }

    public void setTxtMentorTima(javax.swing.JTextField txtMentorTima) {
        this.txtMentorTima = txtMentorTima;
    }

    public javax.swing.JTextField getTxtNazivTima() {
        return txtNazivTima;
    }

    public void setTxtNazivTima(javax.swing.JTextField txtNazivTima) {
        this.txtNazivTima = txtNazivTima;
    }

    public javax.swing.JTextField getTxtSlozenost() {
        return txtSlozenost;
    }

    public void setTxtSlozenost(javax.swing.JTextField txtSlozenost) {
        this.txtSlozenost = txtSlozenost;
    }

    public javax.swing.JTable getTblClanovi() {
        return tblClanovi;
    }

    public void setTblClanovi(javax.swing.JTable tblClanovi) {
        this.tblClanovi = tblClanovi;
    }

    public javax.swing.JLabel getLblErrorDizajn() {
        return lblErrorDizajn;
    }

    public void setLblErrorDizajn(javax.swing.JLabel lblErrorDizajn) {
        this.lblErrorDizajn = lblErrorDizajn;
    }

    public javax.swing.JLabel getLblErrorSlozenost() {
        return lblErrorSlozenost;
    }

    public void setLblErrorSlozenost(javax.swing.JLabel lblErrorSlozenost) {
        this.lblErrorSlozenost = lblErrorSlozenost;
    }

    public javax.swing.JLabel getLblErrprEfikasnost() {
        return lblErrprEfikasnost;
    }

    public void setLblErrprEfikasnost(javax.swing.JLabel lblErrprEfikasnost) {
        this.lblErrprEfikasnost = lblErrprEfikasnost;
    }

    public javax.swing.JButton getBtnOtkazi() {
        return btnOtkazi;
    }

    public void setBtnOtkazi(javax.swing.JButton btnOtkazi) {
        this.btnOtkazi = btnOtkazi;
    }




}
