/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import communication.KomunikacijaSaServerom;
import controller.GUIKordinator;
import domain.Clan;
import java.awt.Color;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.table.model.ClanoviTableModel;

/**
 *
 * @author Nikola
 */
public class PnlClanoviPregled extends javax.swing.JPanel {

    /**
     * Creates new form PnlClanoviPregled
     */
    public PnlClanoviPregled() throws Exception {
        initComponents();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFilter = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPregled = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        lblErrorPretraga = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregled clanova"));

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        btnPretraga.setText("Pretraga");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        tblPregled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPregled);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretrazi:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFilter)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addComponent(lblErrorPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnObrisi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        // TODO add your handling code here:
        if (validacija()) {
            try {
                String s = "" + txtFilter.getText();
                List<Clan> lista = KomunikacijaSaServerom.getInstanca().vratiClanoveZaPretragu(s);
                tblPregled.setModel(new ClanoviTableModel(lista));

                izbrisi();
                //isprazni();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da izvrsi pretragu!", "Greska", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(PnlHakatonPregled.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        try {
            ClanoviTableModel ttm = (ClanoviTableModel) tblPregled.getModel();
            if (tblPregled.getSelectedRow() != -1) {
                Clan c = ttm.getClan(tblPregled.getSelectedRow());
                GUIKordinator.getInstance().getMap().put("izabrani_clan", c);
                FrmDetaljiClana f = new FrmDetaljiClana((Frame) SwingUtilities.getWindowAncestor(this), true, ModFormeDetalji.SHOW);
                f.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Izaberite clana", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception ex) {
            Logger.getLogger(PnlMentorPregled.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem ne moze da prikaze detalje o clanu", "Greska", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
        try {
            if (validacijaTabele()) {
                ClanoviTableModel ctm = (ClanoviTableModel) tblPregled.getModel();
                Clan c = ctm.getClan(tblPregled.getSelectedRow());
                KomunikacijaSaServerom.getInstanca().obrisiClana(c);
                JOptionPane.showMessageDialog(this, "Sistem je obrisao clana", "Uspesno", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Izaberite clana", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise clana", "Uspesno", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        try {
            // TODO add your handling code here:
            String s = "" + txtFilter.getText();
            List<Clan> lista = KomunikacijaSaServerom.getInstanca().vratiClanoveZaPretragu(s);
            tblPregled.setModel(new ClanoviTableModel(lista));
        } catch (Exception ex) {
            Logger.getLogger(PnlClanoviPregled.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtFilterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorPretraga;
    private javax.swing.JTable tblPregled;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnDetalji() {
        return btnDetalji;
    }

    public void setBtnDetalji(javax.swing.JButton btnDetalji) {
        this.btnDetalji = btnDetalji;
    }

    public javax.swing.JButton getBtnObrisi() {
        return btnObrisi;
    }

    public void setBtnObrisi(javax.swing.JButton btnObrisi) {
        this.btnObrisi = btnObrisi;
    }

    public javax.swing.JButton getBtnPretraga() {
        return btnPretraga;
    }

    public void setBtnPretraga(javax.swing.JButton btnPretraga) {
        this.btnPretraga = btnPretraga;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JLabel getLblErrorPretraga() {
        return lblErrorPretraga;
    }

    public void setLblErrorPretraga(javax.swing.JLabel lblErrorPretraga) {
        this.lblErrorPretraga = lblErrorPretraga;
    }

    public javax.swing.JTable getTblPregled() {
        return tblPregled;
    }

    public void setTblPregled(javax.swing.JTable tblPregled) {
        this.tblPregled = tblPregled;
    }

    public javax.swing.JTextField getTxtFilter() {
        return txtFilter;
    }

    public void setTxtFilter(javax.swing.JTextField txtFilter) {
        this.txtFilter = txtFilter;
    }

    private boolean validacija() {
        boolean pom = true;
        izbrisi();
        if (txtFilter.getText().isEmpty()) {
            lblErrorPretraga.setText("Unesite pretragu!");
            pom = false;
        }
        return true;
    }

    private void izbrisi() {
        lblErrorPretraga.setText("");
        lblErrorPretraga.setForeground(Color.red);
    }

    private void isprazni() {
        txtFilter.setText("");
    }

    private boolean validacijaTabele() {
        return tblPregled.getSelectedRow() != -1;
    }

    private void preparePanel() throws Exception {
        srediTabelu();
    }

    private void srediTabelu() throws Exception {
        List<Clan> lista = KomunikacijaSaServerom.getInstanca().vratiClanove();
        tblPregled.setModel(new ClanoviTableModel(lista));
    }
}
