/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import communication.KomunikacijaSaServerom;
import domain.Hakaton;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.table.model.HakatoniTableModel;

/**
 *
 * @author Nikola
 */
public class PnlHakatonPregled extends javax.swing.JPanel {

    /**
     * Creates new form pnlHkaton
     */
    public PnlHakatonPregled() throws Exception {
        initComponents();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilter = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPregled = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        lblErrorPretraga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga hakatona"));

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        btnPretraga.setText("Pretraga");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        tblPregled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPregled);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretrazi:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFilter)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPretraga))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalji)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        // TODO add your handling code here:
        try {

            if (validacijaTabele()) {
                HakatoniTableModel htm = (HakatoniTableModel) tblPregled.getModel();
                Hakaton h = htm.getHakaton(tblPregled.getSelectedRow());
                FrmAdminDetaljiHakaton fDetalji = new FrmAdminDetaljiHakaton((FrmAdminGlavna) SwingUtilities.getWindowAncestor(this), true, h);
                fDetalji.setVisible(true);
            } else {

                JOptionPane.showMessageDialog(this, "Izaberite hakaton!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                HakatoniTableModel htm = (HakatoniTableModel) tblPregled.getModel();
                List<Hakaton> lista = htm.getLista();
                if (!lista.isEmpty()) {
                    tblPregled.setRowSelectionInterval(0, 0);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne moze da prikaze detalje o hakatonu.", "Greska", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        // TODO add your handling code here:

        if (validacija()) {
            try {
                String s = txtFilter.getText();
                List<Hakaton> lista = KomunikacijaSaServerom.getInstanca().vratiHakatone(s);
                tblPregled.setModel(new HakatoniTableModel(lista));

                izbrisi();
                //JOptionPane.showMessageDialog(this, "Sistem ne moze da izvrsi pretragu.", "Greska", JOptionPane.ERROR_MESSAGE);

                //isprazni();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da izvrsi pretragu.", "Greska", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(PnlHakatonPregled.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        try {
            // TODO add your handling code here:
            String s = "" + txtFilter.getText();
            List<Hakaton> lista = KomunikacijaSaServerom.getInstanca().vratiHakatone(s);
            tblPregled.setModel(new HakatoniTableModel(lista));
        } catch (Exception ex) {
            Logger.getLogger(PnlHakatonPregled.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtFilterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorPretraga;
    private javax.swing.JTable tblPregled;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnDetalji() {
        return btnDetalji;
    }

    public void setBtnDetalji(javax.swing.JButton btnDetalji) {
        this.btnDetalji = btnDetalji;
    }

    public javax.swing.JButton getBtnPretraga() {
        return btnPretraga;
    }

    public void setBtnPretraga(javax.swing.JButton btnPretraga) {
        this.btnPretraga = btnPretraga;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JTable getTblPregled() {
        return tblPregled;
    }

    public void setTblPregled(javax.swing.JTable tblPregled) {
        this.tblPregled = tblPregled;
    }

    public javax.swing.JTextField getTxtFilter() {
        return txtFilter;
    }

    public void setTxtFilter(javax.swing.JTextField txtFilter) {
        this.txtFilter = txtFilter;
    }

    private void preparePanel() throws Exception {
        //lblPrijavljeniAdmin.setText("Prijavljeni administrator : " + GUIKordinator.getInstance().getMap().get("active_user"));
        srediTabelu();
    }

    private void srediTabelu() throws Exception {
        String s = txtFilter.getText();
        List<Hakaton> listaHakatona = KomunikacijaSaServerom.getInstanca().vratiHakatone(s);
        tblPregled.setModel(new HakatoniTableModel(listaHakatona));

    }

    public javax.swing.JLabel getLblErrorPretraga() {
        return lblErrorPretraga;
    }

    public void setLblErrorPretraga(javax.swing.JLabel lblErrorPretraga) {
        this.lblErrorPretraga = lblErrorPretraga;
    }

    private boolean validacija() {
        boolean pom = true;
        izbrisi();
        if (txtFilter.getText().isEmpty()) {
            lblErrorPretraga.setText("Unesite pretragu!");
            pom = false;
        }
        return true;
    }

    private void izbrisi() {
        lblErrorPretraga.setText("");
        lblErrorPretraga.setForeground(Color.red);
    }

    private void isprazni() {
        txtFilter.setText("");
    }

    private boolean validacijaTabele() {
        int selectedRow = tblPregled.getSelectedRow();
        return selectedRow != -1;

    }

}
